import type { Metadata } from "next";
import Link from "next/link";
import { generatePageMeta, generateBreadcrumbSchema } from "@/lib/seo";

export const metadata: Metadata = generatePageMeta(
  "Terms & Conditions | MorseCode.World",
  "Terms and conditions for using MorseCode.World. Read our terms of service and usage guidelines.",
  "/terms",
  ["terms and conditions", "morsecode.world terms", "terms of service"]
);

export default function TermsPage() {
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "https://morsecode.world" },
    { name: "Terms & Conditions", url: "https://morsecode.world/terms" },
  ]);

  return (
    <main className="min-h-screen">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-8 md:py-12">
        <nav className="flex items-center gap-2 text-sm text-slate-500 mb-6" aria-label="Breadcrumb">
          <Link href="/" className="hover:text-green-600 transition-colors">Home</Link>
          <span className="text-slate-400">/</span>
          <span className="text-slate-900 font-medium">Terms &amp; Conditions</span>
        </nav>

        <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-8">Terms &amp; Conditions</h1>

        <div className="prose prose-slate max-w-none space-y-6 text-slate-700 leading-relaxed">
          <p><strong>Last updated:</strong> December 15, 2024</p>

          <h2 className="text-xl font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing and using MorseCode.World (the &quot;Service&quot;), you agree to be bound by these Terms
            and Conditions. If you do not agree with any part of these terms, you should not use the Service.
          </p>

          <h2 className="text-xl font-bold text-slate-900">2. Description of Service</h2>
          <p>
            MorseCode.World provides free online Morse code translation tools, educational content, reference charts,
            quizzes, and blog articles. The Service is provided &quot;as is&quot; and &quot;as available&quot;
            without warranties of any kind.
          </p>

          <h2 className="text-xl font-bold text-slate-900">3. Use of the Service</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these terms. You agree not to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Use the Service in any way that violates applicable laws or regulations</li>
            <li>Attempt to gain unauthorized access to any portion of the Service</li>
            <li>Use automated means to access the Service or collect information</li>
            <li>Reproduce, duplicate, or copy any content for commercial redistribution without permission</li>
            <li>Interfere with or disrupt the Service&apos;s infrastructure</li>
          </ul>

          <h2 className="text-xl font-bold text-slate-900">4. Intellectual Property</h2>
          <p>
            All content on MorseCode.World, including text, graphics, logos, and software, is the property of
            MorseCode.World and is protected by intellectual property laws. You may use the Service and its
            content for personal, non-commercial purposes. The Morse code translation output generated by the
            Service may be freely used for any purpose.
          </p>

          <h2 className="text-xl font-bold text-slate-900">5. Accuracy of Information</h2>
          <p>
            While we strive to provide accurate Morse code translations following the International Morse Code
            standard (ITU-R M.1677), we make no guarantees about the accuracy of translations. Morse code
            generated by the Service should be verified before use in critical applications such as emergency
            signaling.
          </p>

          <h2 className="text-xl font-bold text-slate-900">6. Limitation of Liability</h2>
          <p>
            MorseCode.World shall not be liable for any direct, indirect, incidental, special, or consequential
            damages arising from the use of or inability to use the Service. This includes, but is not limited
            to, damages for loss of data, goodwill, or other intangible losses.
          </p>

          <h2 className="text-xl font-bold text-slate-900">7. Emergency Disclaimer</h2>
          <p>
            The Morse code tools and information provided on this website are for educational and personal use.
            In genuine emergency situations, always rely on officially recognized distress signals and
            communication methods. We are not responsible for any consequences arising from the use of our
            Service in emergency situations.
          </p>

          <h2 className="text-xl font-bold text-slate-900">8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms and Conditions at any time. Changes will be effective
            immediately upon posting. Your continued use of the Service after changes are posted constitutes
            acceptance of the modified terms.
          </p>

          <h2 className="text-xl font-bold text-slate-900">9. Contact</h2>
          <p>
            For questions about these Terms, please visit our{" "}
            <Link href="/contact" className="text-green-600 underline">contact page</Link>.
          </p>
        </div>
      </div>
    
        {/* Popular Tools */}
        <section className="mt-12">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Popular Morse Code Tools</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            <Link href="/morse-code-translator" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              🔤 Translator
            </Link>
            <Link href="/morse-code-decoder" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              🔓 Decoder
            </Link>
            <Link href="/morse-code-alphabet" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              📋 Alphabet
            </Link>
            <Link href="/learn-morse-code" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              📖 Learn
            </Link>
            <Link href="/morse-code-quiz" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              🎯 Quiz
            </Link>
            <Link href="/contact" className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 font-medium hover:bg-green-100 transition-colors">
              ✉️ Contact Us
            </Link>
          </div>
        </section>
      </main>
  );
}
